/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  // All Tailwind utilities get a tw- prefix to avoid conflicts with Bootstrap and existing CSS
  prefix: 'tw-',
  // Disable Tailwind's base reset - Bootstrap Reboot owns the base styles
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        m3: {
          "on-secondary": "#ffffff",
          "inverse-surface": "#2d3037",
          "surface": "#f9f9ff",
          "primary-container": "#0074db",
          "on-primary": "#ffffff",
          "on-primary-fixed-variant": "#004689",
          "primary": "#005baf",
          "on-primary-container": "#fefcff",
          "on-background": "#181c22",
          "inverse-primary": "#a8c8ff",
          "secondary": "#5c5f60",
          "error-container": "#ffdad6",
          "on-primary-fixed": "#001b3c",
          "primary-fixed-dim": "#a8c8ff",
          "inverse-on-surface": "#eef0fa",
          "error": "#ba1a1a",
          "surface-dim": "#d8dae3",
          "secondary-fixed-dim": "#c5c7c8",
          "surface-tint": "#005eb4",
          "surface-container-lowest": "#ffffff",
          "on-secondary-fixed": "#191c1d",
          "on-secondary-fixed-variant": "#454748",
          "on-tertiary-fixed": "#301400",
          "tertiary-fixed": "#ffdcc6",
          "on-error-container": "#93000a",
          "tertiary-fixed-dim": "#ffb785",
          "surface-bright": "#f9f9ff",
          "on-secondary-container": "#626566",
          "surface-container-highest": "#e0e2eb",
          "on-tertiary-container": "#fffbff",
          "on-surface": "#181c22",
          "surface-container-low": "#f1f3fc",
          "secondary-container": "#e1e3e4",
          "background": "#f9f9ff",
          "outline-variant": "#c1c6d5",
          "surface-variant": "#e0e2eb",
          "tertiary-container": "#b65c00",
          "on-surface-variant": "#414753",
          "outline": "#717784",
          "on-tertiary": "#ffffff",
          "on-error": "#ffffff",
          "surface-container-high": "#e6e8f1",
          "secondary-fixed": "#e1e3e4",
          "primary-fixed": "#d5e3ff",
          "on-tertiary-fixed-variant": "#713700",
          "surface-container": "#ecedf7",
          "tertiary": "#914800"
        },
        brand: {
          blue: '#3095EC',
          'blue-soft': '#dfeefe',
          'blue-dark': '#2E7FF0',
          bg: '#ECEFF7',
          card: '#e8edf7',
          ink: '#1E1E1E',
          muted: '#606977',
          line: '#cad2e0',
          danger: '#ef4a42',
        },
      },
      fontFamily: {
        karla: ['Karla', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      screens: {
        sm: '430px',
        md: '768px',
        lg: '992px',
        xl: '1400px',
      },
      fontSize: {
        xs: ['11px', { lineHeight: '1.4', fontWeight: '600' }],
        sm: ['13px', { lineHeight: '1.45', fontWeight: '600' }],
        base: ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        lg: ['18px', { lineHeight: '1.6', fontWeight: '600' }],
        xl: ['20px', { lineHeight: '1.65', fontWeight: '600' }],
        '2xl': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        '3xl': ['28px', { lineHeight: '1.1', fontWeight: '700' }],
        '4xl': ['36px', { lineHeight: '1.0', fontWeight: '800' }],
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '7': 'var(--space-7)',
        '8': 'var(--space-8)',
        sidebar: '260px',
        'sidebar-collapsed': '72px',
      },
      borderRadius: {
        pill: '999px',
        xl: '20px',
        lg: '16px',
        md: '12px',
      },
      boxShadow: {
        soft: '0 16px 36px rgba(35, 61, 107, 0.12)',
        card: '0 4px 16px rgba(35, 61, 107, 0.08)',
        sidebar: '4px 0 24px rgba(35, 61, 107, 0.08)',
      },
      transitionDuration: {
        250: '250ms',
      },
      maxWidth: {
        'screen-content': '1400px',
      },
    },
  },
  plugins: [
    // @tailwindcss/forms plugin is disabled since Bootstrap handles form styles
  ],
};
